import React, { useEffect } from 'react';
import { MapContainer, TileLayer, CircleMarker, Circle, Popup, Polyline, Marker, useMap } from 'react-leaflet';
import { divIcon } from 'leaflet';
import { Hospital, House } from 'lucide-react';

type Props = { incidents:any[]; shelters:any[]; hospitals:any[]; routes?:any[]; showIncidents?:boolean; compact?:boolean; showHazards?:boolean; center?:[number,number] };

function Recenter({center}:{center:[number,number]}){ const map=useMap(); useEffect(()=>{ map.flyTo(center, center[0]===21.2514 && center[1]===81.6296 ? 11 : 10, {duration:0.8}); },[center,map]); return null; }

const routeMeta:any = {
  EVACUATION:{emoji:'🚗', label:'CIVILIAN EVACUATION', color:'#f4b400'},
  AMBULANCE:{emoji:'🚑', label:'AMBULANCE', color:'#55a3ff'},
  RESCUE:{emoji:'🛟', label:'NDRF / RESCUE', color:'#28a36a'},
  POLICE:{emoji:'🚓', label:'POLICE', color:'#3867d6'},
  FIRE:{emoji:'🚒', label:'FIRE BRIGADE', color:'#e24b3b'},
  JCB:{emoji:'🚜', label:'JCB / HEAVY EQUIPMENT', color:'#e58b24'},
  CRANE:{emoji:'🏗️', label:'CRANE / HEAVY RESCUE', color:'#a35bd6'},
};
const emojiIcon=(emoji:string)=>divIcon({className:'route-emoji-marker',html:`<span>${emoji}</span>`,iconSize:[30,30],iconAnchor:[15,15]});
const hazardIcon=(emoji:string)=>divIcon({className:'hazard-emoji-marker',html:`<span>${emoji}</span>`,iconSize:[40,40],iconAnchor:[20,20]});
function hazardEmoji(type:string){ const t=String(type).toUpperCase(); if(t.includes('FLOOD')) return '🌊'; if(t.includes('FIRE')||t.includes('WILDFIRE')) return '🔥'; if(t.includes('CYCLONE')) return '🌀'; if(t.includes('EARTH')) return '〰️'; if(t.includes('LANDSLIDE')) return '⛰️'; if(t.includes('RAIN')) return '🌧️'; if(t.includes('HEAT')) return '🌡️'; return '⚠️'; }

export default function MapView({incidents,shelters,hospitals,routes=[],showIncidents=true,compact=false,showHazards=true,center=[21.2514,81.6296]}:Props){
  return <div className={`map-wrap ${compact?'compact':''}`}>
    <MapContainer center={center} zoom={11} scrollWheelZoom className="map"><Recenter center={center} />
      <TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
      {(shelters || []).map((s:any)=><CircleMarker key={s.id} center={[s.lat,s.lon]} radius={8} pathOptions={{color:'#178b63',fillColor:'#39c58b',fillOpacity:.85}}><Popup><b><House size={14} style={{verticalAlign:'middle'}}/> 🏠 {s.name}</b><br/>Available: {s.capacity-s.occupancy}</Popup></CircleMarker>)}
      {(hospitals || []).map((h:any)=><CircleMarker key={h.id} center={[h.lat,h.lon]} radius={8} pathOptions={{color:'#2466d1',fillColor:'#55a3ff',fillOpacity:.9}}><Popup><b><Hospital size={14} style={{verticalAlign:'middle'}}/> 🏥 {h.name}</b><br/>{h.open?'OPEN':'CLOSED'}</Popup></CircleMarker>)}
      {showHazards && showIncidents && (incidents || []).map((i:any)=>{ const risk=String(i.severity).toUpperCase(); const radius=risk==='CRITICAL'?Math.min(9000,Math.max(1800,Math.sqrt(Math.max(1,Number(i.affected_population||0)))*18)):risk==='HIGH'?Math.min(7000,Math.max(1400,Math.sqrt(Math.max(1,Number(i.affected_population||0)))*15)):Math.min(5000,Math.max(1000,Math.sqrt(Math.max(1,Number(i.affected_population||0)))*12)); const stroke=risk==='CRITICAL'?'#ef4444':risk==='HIGH'?'#f97316':'#f59e0b'; return <React.Fragment key={`hazard-group-${i.incident_id}`}><Circle key={`hazard-${i.incident_id}`} center={[i.latitude,i.longitude]} radius={radius} pathOptions={{color:stroke,fillColor:stroke,fillOpacity:.12,weight:2,dashArray:'7 6'}}><Popup><b>{hazardEmoji(i.disaster_type)} {risk} HAZARD ZONE</b><br/>{i.disaster_type} · {i.district}<br/>Estimated exposure: {Number(i.affected_population||0).toLocaleString()} people</Popup></Circle><Marker position={[i.latitude,i.longitude]} icon={hazardIcon(hazardEmoji(i.disaster_type))}><Popup><b>{hazardEmoji(i.disaster_type)} HAZARD POINT</b><br/>{i.disaster_type} · {i.district}<br/>{risk} · {Number(i.affected_population||0).toLocaleString()} affected</Popup></Marker></React.Fragment> })}
      {(routes || []).map((r:any)=>{ const meta=routeMeta[r.route_type]||routeMeta.EVACUATION; const path=r.path?.length?r.path:[[r.origin_lat,r.origin_lon],[r.destination_lat,r.destination_lon]]; const mid=path[Math.floor(path.length/2)]||path[0]; const originEmoji=r.route_type==='EVACUATION'?'📍':meta.emoji; const destinationEmoji=r.route_type==='EVACUATION'?'🏠':r.route_type==='AMBULANCE'?'🏥':'📍'; const sourceLabel=r.route_type==='EVACUATION'?'Civilian / affected area':'Response base'; const destinationLabel=r.route_type==='EVACUATION'?'Relief shelter':meta.label+' destination'; return <React.Fragment key={r.route_id}><Polyline positions={path} pathOptions={{color:meta.color,weight:5,opacity:.9,dashArray:r.status==='PLANNED'?'9 7':undefined}}><Popup className="route-popup"><div className="map-popup-detail"><b>{meta.emoji} {meta.label} ROUTE</b><span>Distance: {r.distance_km} km</span><span>Estimated time: {r.eta_minutes} min</span><span>Status: {r.status}</span><span>Source: {r.official?'Official':'Simulation'}</span></div></Popup></Polyline><Marker position={mid as [number,number]} icon={emojiIcon(meta.emoji)}><Popup className="route-popup"><div className="map-popup-detail"><b>{meta.emoji} {meta.label}</b><span>This marker represents the active {meta.label.toLowerCase()} movement corridor.</span><span>Distance: {r.distance_km} km · ETA: {r.eta_minutes} min</span><span>Status: {r.status} · {r.official?'Official route':'Simulation route'}</span></div></Popup></Marker><Marker position={[r.origin_lat,r.origin_lon]} icon={emojiIcon(originEmoji)}><Popup className="route-popup"><div className="map-popup-detail"><b>{originEmoji} {sourceLabel}</b><span>{r.route_type==='EVACUATION'?'People are being guided from the affected area toward the designated relief shelter.':'Response assets are being coordinated from this point toward the incident.'}</span><span>Route: {meta.label}</span><span>Status: {r.status}</span></div></Popup></Marker><Marker position={[r.destination_lat,r.destination_lon]} icon={emojiIcon(destinationEmoji)}><Popup className="route-popup"><div className="map-popup-detail"><b>{destinationEmoji} {destinationLabel}</b><span>{r.route_type==='EVACUATION'?'Designated destination for the evacuation movement.':'Destination point for the response operation.'}</span><span>Distance: {r.distance_km} km · ETA: {r.eta_minutes} min</span><span>{r.official?'Official route':'Simulation route'}</span></div></Popup></Marker></React.Fragment>})}
    </MapContainer>
    <div className="map-legend"><span><i className="dot shelter"/> 🏠 Shelter</span><span><i className="dot hospital"/> 🏥 Hospital</span>{showIncidents&&<span><i className="dot incident"/> 📍 Hazard point</span>}{showHazards&&showIncidents&&<span><i className="dot hazard"/> Hazard zone</span>}{(routes || []).length>0&&<span>🚗 Civilian</span>}{(routes || []).some((r:any)=>r.route_type==='AMBULANCE')&&<span>🚑 Ambulance</span>}{(routes || []).some((r:any)=>r.route_type==='POLICE')&&<span>🚓 Police</span>}{(routes || []).some((r:any)=>r.route_type==='FIRE')&&<span>🚒 Fire</span>}{(routes || []).some((r:any)=>r.route_type==='RESCUE')&&<span>🛟 NDRF</span>}{(routes || []).some((r:any)=>r.route_type==='JCB')&&<span>🚜 JCB</span>}{(routes || []).some((r:any)=>r.route_type==='CRANE')&&<span>🏗️ Crane</span>}</div>
  </div>
}
